{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "tracker.serviceAccountName" . }}
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
{{- end -}}
