apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extractor.fullname" . }}
  labels:
    {{- include "extractor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "extractor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "extractor.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "extractor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.tls.secretName }}
        - name: server-certs
          secret:
            secretName: {{ .Values.tls.secretName }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "extractor.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            {{- if .Values.tls.secretName }}
            - mountPath: /etc/ssl/server/
              name: server-certs
            {{- end }}
          args:
            - --port=8090
            {{- if .Values.tls.secretName }}
            - --tls-ca=/etc/ssl/server/ca.crt
            - --tls-cert=/etc/ssl/server/tls.crt
            - --tls-key=/etc/ssl/server/tls.key
            {{- end }}
            {{- range $disabledManifest := .Values.disabledManifests }}
            - --disabled-manifests={{ $disabledManifest }}
            {{- end }}
          ports:
            - name: grpc
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 5
          readinessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
