version: "3.7"

services:
  mysql:
    restart: always
    image: mysql:8
    hostname: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: depscloud
    expose:
      - 3306

  tracker:
    restart: always
    image: depscloud/tracker:latest
    hostname: tracker
    depends_on:
      - mysql
    volumes:
      - ./certs:/etc/depscloud/certs
    command:
      - --storage-driver=mysql
      - --storage-address=user:password@tcp(mysql:3306)/depscloud
      - --tls-key=/etc/depscloud/certs/tracker.key
      - --tls-cert=/etc/depscloud/certs/tracker.crt
      - --tls-ca=/etc/depscloud/certs/ca.crt

  extractor:
    restart: always
    image: depscloud/extractor:latest
    hostname: extractor
    volumes:
      - ./certs:/etc/depscloud/certs
    command:
      - --tls-key=/etc/depscloud/certs/extractor.key
      - --tls-cert=/etc/depscloud/certs/extractor.crt
      - --tls-ca=/etc/depscloud/certs/ca.crt
    
  indexer:
    restart: on-failure
    image: depscloud/indexer:latest
    hostname: indexer
    depends_on:
      - extractor
      - tracker
    volumes:
      - ./certs:/etc/depscloud/certs
      - ./config.yaml:/etc/indexer/config.yaml
    command:
      - --cron
      - --workers=1
      - --rds-config=/etc/indexer/config.yaml
      - --extractor-key=/etc/depscloud/certs/indexer.key
      - --extractor-cert=/etc/depscloud/certs/indexer.crt
      - --extractor-ca=/etc/depscloud/certs/ca.crt
      - --tracker-key=/etc/depscloud/certs/indexer.key
      - --tracker-cert=/etc/depscloud/certs/indexer.crt
      - --tracker-ca=/etc/depscloud/certs/ca.crt

  gateway:
    restart: always
    image: depscloud/gateway:latest
    hostname: gateway
    depends_on:
      - extractor
      - tracker
    volumes:
      - ./certs:/etc/depscloud/certs
    command:
      - --tls-key=/etc/depscloud/certs/localhost.key
      - --tls-cert=/etc/depscloud/certs/localhost.crt
      - --tls-ca=/etc/depscloud/certs/ca.crt
      - --extractor-key=/etc/depscloud/certs/gateway.key
      - --extractor-cert=/etc/depscloud/certs/gateway.crt
      - --extractor-ca=/etc/depscloud/certs/ca.crt
      - --tracker-key=/etc/depscloud/certs/gateway.key
      - --tracker-cert=/etc/depscloud/certs/gateway.crt
      - --tracker-ca=/etc/depscloud/certs/ca.crt
    ports:
      - 8080:8080
