name: tracker-integration

on:
  pull_request:
    paths:
      - ".github/workflows/tracker-integration.yaml"
      - "tracker/**"
  push:
    branches:
      - "main"

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database:
          - driver: sqlite
            address: file::memory:?cache=shared
          - driver: mysql
            address: user:password@tcp(depscloud-mysql:3306)/depscloud
          - driver: postgres
            address: postgres://user:password@depscloud-postgresql:5432/depscloud
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.0.0
        with:
          minikube version: 'v1.12.3'
          kubernetes version: 'v1.18.2'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm

      # Build a development version of the application on the minikube cluster
      - name: Build Container
        run: |
          eval $(minikube docker-env)
          make tracker

      # Deploy the ecosystem using existing the helm chart and force the use
      # of the docker local image.
      - name: Deploy Ecosystem
        run: |
          helm repo add depscloud https://depscloud.github.io/deploy/charts
          helm upgrade -i depscloud depscloud/depscloud \
            --set tracker.image.pullPolicy=Never \
            --set tracker.image.tag=latest \
            --set ${{ matrix.database.driver }}.enabled=true \
            --set mysql.db.user=user \
            --set mysql.db.password=password \
            --set mysql.db.name=depscloud \
            --set postgres.postgresqlUsername=user \
            --set postgres.postgresqlPassword=password \
            --set postgres.postgresqlDatabase=depscloud \
            --set "tracker.storage.driver=${{ matrix.database.driver }}" \
            --set "tracker.storage.address=${{ matrix.database.address }}"

          kubectl rollout status -w --timeout 300s deployment/depscloud-extractor
          kubectl rollout status -w --timeout 300s deployment/depscloud-tracker
          kubectl rollout status -w --timeout 300s deployment/depscloud-gateway

          kubectl wait --for=condition=complete --timeout=300s job/depscloud-indexer
          kubectl logs -l job-name=depscloud-indexer
